[package]
name = "gm-autorestart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a2s = "0.5.2"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
